repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: pretty-format-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: mixed-line-ending
  - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.3
  hooks:
  - id: python-safety-dependencies-check
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.1
  hooks:
  - id: bandit
    args: [--configfile, bandit.yaml]

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-docstrings
    - flake8-black
    - flake8-bugbear
    - flake8-django
    - flake8-pytest-style

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    entry: isort --profile=black

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
