version: '3'

services:

  backend:
    container_name: {{cookiecutter.project_name}}_backend
    restart: on-failure
    build: .
    volumes:
    - .:/code
    ports:
    - 8000:8000
    environment:
    - DJANGO_SECRET_KEY='local'
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=db
    - DJANGO_SETTINGS_MODULE={{cookiecutter.project_name}}.{{cookiecutter.project_name}}.settings
    - DJANGO_CONFIGURATION=Dev
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py create_super_user --username admin --password Passw0rd &&
      python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db

  db:
    image: postgres
    container_name: {{cookiecutter.project_name}}_db
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
